- inc/functions.php
> Added a str_replace to replace \ by /

- front/object.form.php
Show correct item with Option case
> Fix the breadcrumb on object.form.php

- inc/object.class.php
- objects/generic.class.tpl
see #114 
The bug also affected other tabs 
- Problems
- Project Tasks
> avoid overwrite of CommonDBTM::$rightname from subclasses

- inc/type.class.php
With $rightname you have the inherent of parent entity (function getRights not usefull)
> Better management of rights

- inc/type.class.php
$DB used, but not declared as a global
> fix use of global var

- inc/type.class.php
Locale files will now be generated with same base content.
> Fix generated locales; fixes #174

- genericobject.xml
Added short and long description in Czech language, as well as keywords and language code into list of localization.
> I10n - added Czech translation into xml

- inc/type.class.php
This is required to auto regenerate injection file in update process. Will be usefull for https://github.com/pluginsGLPI/genericobject/pull/211.
> Force regeneration of injection class when overwrite required

- objects/locale.tpl
> Remove "Do not edit this file"

- inc/field.class.php
- inc/object.class.php
Q | A
-- | --
Bug fix? | no
New feature? | yes
BC breaks? | no
Deprecations? | no
Tests pass? | yes
Fixed tickets | #217
Add a new field type for inserting empty space in custom object forms. For details, see ticket #217
> Add field definition for empty space

- inc/object.class.php
- inc/type.class.php
Required to enable autocomplete on GLPI 9.4.4+ (see https://github.com/glpi-project/glpi/commit/339b856273f2cf5cb409e6db1a2689a418c5a051)
> Whitelist autocomplete fields

- inc/object.class.php
Fix bad call to getObjectSearchOptions (have been replace by rawSearchOptions)
see https://github.com/pluginsGLPI/treeview/issues/24
Best regards
> fix(hook): fix treeview hook

- hook.php
- inc/field.class.php
Fix locales include
see internal 21204
> fix(core): fix include locales

- inc/field.class.php
- inc/object.class.php
- inc/type.class.php
- setup.php
Here is a PR for adding the component tab in objects
> Fix #287 - Add component Tab

- inc/type.class.php
- setup.php
Expose generic objects to Formcreator, in question of type Glpi Object
> feat(type): hook to expose generic objects to Formcreator

- inc/object.class.php
Fix display of tab reservation for object
```fullcalendar``` and ```reservations``` JS lib are not loaded
Prevent error from browser console
Fix : (portal) !6633
> fix(reservation): fix display of reservation tab fom object

- front/field.form.php
count correctly the number of fields to get a proper page after click on delete button.... i htink it was a miss typo.
> Fix field deletion

- front/type.form.php
Method has been removed in 2cbaf4dc12df40f0a322081dcc67adad68a4c20c (2011)
> Method has been removed

- inc/typefamily.class.php
Like https://github.com/pluginsGLPI/genericobject/pull/358
but for object inside family
before : 
after :
> fix object entries ordering

- CHANGELOG.md
- front/familylist.php
instead listing all items of a family, and on click get 'you don't have access' error message, juste remove it from the listing.
> Update familylist.php to don't show items that user don't have right access

- CHANGELOG.md
- inc/object.class.php
- It fixes !37462
Prevent php warning
```
PHP User Warning (512): Unknown attributes "itemdevicedrive_types", "itemdevicecontrol_types" used in "PluginGenericobjectCamera" class registration in /var/www/host/src/Plugin.php at line 1667
``` 
Since https://github.com/pluginsGLPI/genericobject/pull/420
GLPI fix have been added
https://github.com/glpi-project/glpi/pull/19214
So we need to check glpi version before add `"itemdevicedrive_types", "itemdevicecontrol_types"` before call `Plugin::registerClass`
We need a new release after merged
> fix(Object): fix warning
