inc/type.class.php

Attempt give a 1 char typename makes the plugin fail. 2 chars is OK, and 1 char is meaningless.
Also Fix a comment

add check when adding a new object

---

inc/object.class.php
inc/type.class.php

- add linkfield to search options only when needed
- this makes the argument on
PluginGenericobjectObject::getobjectSearchOptions() useless
- re-enable the checkbox to enable field unicity
- reorder search options by key (very important)

attempt to repair field unicity feature; see #16

---

inc/type.class.php

Many users have trouble to upgrade their GLPi because  they miss or forget to copy files of the plugin from a old to new instance of GLPi.
I hope this will help them to solve the issue by themselve, help them faster, and produce less support request.
Maybe this would be a good idea to add an hyperlink to a help page.
See #113

Add an upgrade error if the plugin cannot load classes in upgrade

---

inc/profile.class.php

`Profile::displayRightsChoiceMatrix()` displays the matrix after filling it with values corresponding to loaded profile. As there is no function to display a matrix based on multiple profiles, I displayed one matrix per profile to fix this bug quickly.
Maybe it should be enhanced later.

Fix rights matrix display for object; fixes #182

---

inc/type.class.php

Plugin installation requires object classes to update the core `Notepad` table. I just moved the regeneration fo files prior to this update.

Fix plugin installation where files are missing; fixes #158

---

inc/object.class.php

Fix these error messages in log: CommonDBTM::searchOptions() in /opt/bitnami/apps/glpi/htdocs/inc/commondbtm.class.php line 3455
Duplicate key # (field A/field B) in PluginGenericobjectFoo searchOptions!
This also fixes the issue of missing fields in dropdowns for objects created with GenericObjects. For example, fields like serial where not in the list of fields to select when defining duplicity rules. It will probably fix some other issues too, because this affects anything that relies on SearchOptions, like dropdowns related to GenericObjects.
This fix can only ensure that the $options array stops repeating itself. The fix heavily relies on the provided $index_exceptions array to avoid globally reserved indexes.
The $options array repeated itself, because the "$currentindex = …

Fix duplicated search option key bug

---

inc/object.class.php

Signed-off-by: Stanislas <skita@teclib.com>
global search display to result for genericobject
this PR prevent duplicate result on global search

fix(core): fix duplicate result for global search

---

inc/object.class.php

#244 
When you add a name with double s (glass), GLPI cannot correctly check the object's permissions.
Genericobject declares the rightname with sss (plugin_genericobject_glasss) but GLPI searches for ses (plugin_genericobject_glasses).
This causes some tabs not to load correctly, such as Notepad

Fix rightname when object name ends with two "s"

---

inc/object.class.php

MySQL >= 8.0.19 returns `int` instead of `int(11)` in `SHOW COLUMNS` result.

Fix compatibility with MySQL >= 8.0.19; fixes #297

---

inc/object.class.php

1. `unsigned` integers were not detected as `int`, so items dropdowns were not displayed when unsigned keys migration was done.
2. `decimal` was formatted without the `edit` flag, so, depending on user preferences, value was sometimes invalid.

Fix handling of unsigned int and float/decimal fields

---

inc/object.class.php

```Dropdown``` field is not well manage by plugin since it's internal database format change to ```int unsigned```
```Searchoption``` defined this field as test
and ```injection``` process is broken
This PR fix this
Internal ref : !24833

fix(injection): take care of int unsigned

---

front/getimpacticon.php
hook.php
inc/object.class.php
inc/type.class.php
setup.php

Two new configuration options were added to:
- Enable impact analysis for the given type
- Upload a custom icon to be used in the impact analysis
Working example:

Add support for impact analysis

---

inc/object.class.php

When trying to clone an instance of an object (which use Assistance) then a warning is displayed and logged.
```
[2023-05-12 15:02:13] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to clone elements of class Item_devices as it does not extends "CommonDBConnexity" in /home/bugier/public_html/glpi-100a/src/Features/Clonable.php at line 112
Backtrace :
src/Features/Clonable.php:112                      trigger_error()
src/Features/Clonable.php:241                      PluginGenericobjectObject->cloneRelations()
src/Features/Clonable.php:190                      PluginGenericobjectObject->clone()
src/MassiveAction.php:1658                         PluginGenericobjectObject->cloneMultiple()
src/MassiveAction.php:1408 …
```

fix typo breaking cloning feature

---

inc/object.class.php

`Lists` button was missing in created objects

fix: missing Lists button

---

inc/object.class.php

Before:
After:
This happens be we fetch all items (ordered by name) then group them by their family.
The ordering should be done on the family names instead, which can be easily done by sorting the final menu entries.

Fix menu entries ordering

---

inc/object.class.php

Prevent this
```
[2023-09-15 14:28:05] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: uasort(): Argument #1 ($array) must be of type array, null given in /mnt/diskhome/home/htdocs/marketplace/genericobject/inc/object.class.php at line 1264
Backtrace :
...etplace/genericobject/inc/object.class.php:1264 uasort()
src/Html.php:1454                                  PluginGenericobjectObject::getMenuContent()
src/Html.php:1681                                  Html::generateMenuSession()
front/central.php:82                               Html::header()
```
When no family or object has been created (i.e. from installation)
A release will become essential

fix(core): prevent uasort(): Argument #1 () must be of type array, null given

---

inc/object.class.php

Prevent this
```
[2023-09-15 14:28:05] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: uasort(): Argument #1 ($array) must be of type array, null given in /mnt/diskhome/home/htdocs/marketplace/genericobject/inc/object.class.php at line 1264
Backtrace :
...etplace/genericobject/inc/object.class.php:1264 uasort()
src/Html.php:1454                                  PluginGenericobjectObject::getMenuContent()
src/Html.php:1681                                  Html::generateMenuSession()
front/central.php:82                               Html::header()
```
When no family or object has been created (i.e. from installation)
A release will become essential

fix(core): prevent uasort(): Argument #1 () must be of type array, ll given

---

inc/field.class.php
inc/object.class.php

```FormCreator``` allows you to use a ```tag``` targeting a property of the selected object (in a question)
ex : 
```##answer_1.Serial_number##```
To do this, ```Formcreator``` changes language (```en_GB```) and load plugin languages to search for the property in ```searchOption```
See : https://github.com/pluginsGLPI/formcreator/pull/3367
Even if you change your language, the plugin will not take this into account. 
Because ```$GO_FIELDS``` is already computed with the language of the logged-in user
This PR forces the system to compute ```$GO_FIELD``` as soon as it requests the ```searchOption```

fix(lang): reset lang before construct searchoption

---

inc/object.class.php

The alignment of fields in generic objects is different from others. For example, when you add a new field to a generic object with plugin fields, the alignment and style are different.
**Before**
**After**

Fix/ Update alignment to match glpi style

---

CHANGELOG.md
inc/object.class.php

In GLPI, objects ending with ```x``` (e.g. ```PAX```) automatically have their table suffixed with ```es```.
cf ```DbUtils::getPlural()```
In ```GenericObject```, the ```rightname``` computation follows part of this logic
But the case of the object ending with ```x``` is missing.
An object ```PluginGenericObjectPax``` have a table like ```plugin_genericobject_paxes``` (OK) but ```rightname```  is compute as ```plugin_genericobject_paxs``` (NOK) 
for classic use, with only the ```Genericobject``` plugin, rights management is OK
But when plugin ```fields``` create a container (from template) for ```PluginGenericObjectPax```, bad ```rightname``` is used (```plugin_genericobject_paxs```)
And when ```datainjection``` plugin have to handle fields (from ```fields``` plugin) , plugin refuse to …

Fix(Object): fix rightname computation

---

inc/object.class.php

Searching on plugin objects with the map view didn't work, as longitude nor latitude wasn't retrieved.
ref !33107

fix: map search

---

CHANGELOG.md
objects/locale.tpl

Even if, before including the locale file, the plugin calls ```global $LANG```, 
translations are not added to ```$LANG``` (```array```)
You also need to add the ```global $LANG``` to the locale file
This PR adapt the template used to create locale file

Fix(Local): fix local override by adding missing global scope

---

inc/object.class.php

Injecting generic objects into `$CFG_GLPI['state_types']` is useless and can't work 
The corresponding SQL table cannot accept a new `is_visible_xxxx` column (this is GLPI's responsibility in this area).
Updating the field simply doesn't work
```sql
MariaDB [10bugfixes]> explain glpi_states;
+-------------------------------+------------------+------+-----+---------+----------------+
| Field                         | Type             | Null | Key | Default | Extra          |
+-------------------------------+------------------+------+-----+---------+----------------+
| id                            | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name                          | varchar(255)     | YES  | MUL | NULL    | …
```

Fix(Core): remove uselss and non-functional injection

---

CHANGELOG.md
setup.php

- It fixes !35986
improve global performance when using many genericobject
When a GLPI page is loaded (depending of context) a itemtype created by genericobject can be registered at least 9 times (see on ticket page)
With 200 object -> 1800 `registerType` call ..
So before `registerType` (which done many action) check if already register in `$_SESSION`
Before 
After

perf: improve global performance when using many genericobject

---

inc/object.class.php
setup.php

Fix https://github.com/pluginsGLPI/genericobject/pull/417
after discovering that generic objects were no longer reservable  
because `$CFG_GLPI[‘reservation_types’]` is systematically reset to default
Fix #35986

Fix(perf): fix improve perf

---

CHANGELOG.md
fields/field.constant.php
inc/object.class.php
inc/type.class.php
setup.php

- It fixes !34818
- adds the ticket_tco field to the table of each object when the user wants to use tickets. This fixes the bug that prevent TCO from being calculated for genericobject.

fix(TCO): missing ticket_tco field in table object

---

inc/object.class.php

- It fixes !36864
Add
- `itemdevicedrive_types`
- `itemdevicecontrol_types`
Need https://github.com/glpi-project/glpi/pull/19214
I take advantage of this PR to force (from cache context) the register for certain cases (I take advantage of this PR to force the register for certain cases (where it is systematically reset by GLPI on each page).

Fix(Core): fix missing 'Component' option

---

inc/object.class.php

Comments are not correctly displayed in generic objects:
- Comments use mediumtext type
- Add 'form-control' class to get the correct style for comments
- [x ] I have performed a self-review of my code.
- It fixes #401
- Here is a brief description of what this PR does
without fix:
with fix:

handle mediumtext type used in comments

---

fields/field.constant.php

- It fixes #38434
The translations **"Technician in charge of the hardware"** and **"Group in charge of the hardware"** originated from GLPI but no longer exist in the current core.
As a result, they are no longer translated in the plugin.
This PR addresses the issue by referencing the correct gettext translation keys from the updated GLPI core.

Chore(i18n): update translations

---

CHANGELOG.md
composer.json
composer.lock
hook.php
phpstan.neon

- It fixes !38333
- Fields added via the fields plugin to an object coming from the genericobject plugin could not be modified if the user passed through massive actions.

fix(fields): massive actions with Fields plugin

---

inc/profile.class.php
inc/type.class.php
inc/typefamily.class.php
setup.php

Fix plugin name
Fix uninstall process

Fix(Core): Fix plugin name label
